<a href="https://colab.research.google.com/github/maanaav15369/AI/blob/main/pytorch_rnn_based_qa_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [2]:
# tokenize
def tokenize(text):
  text = text.lower()
  text = text.replace('?','')
  text = text.replace("'","")
  return text.split()

In [3]:
tokenize('What is the capital of France?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [4]:
# vocab
vocab = {'<UNK>':0}

In [5]:
def build_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])

  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:

    if token not in vocab:
      vocab[token] = len(vocab)

In [6]:
df.apply(build_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [7]:
len(vocab)

327

In [8]:
# convert words to numerical indices
def text_to_indices(text, vocab):

  indexed_text = []

  for token in tokenize(text):

    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [22]:
text_to_indices("Who is Maanaav Trivedi", vocab)

[10, 2, 34, 35]

In [10]:
import torch
from torch.utils.data import Dataset, DataLoader

In [11]:
class QADataset(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):

    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [12]:
dataset = QADataset(df, vocab)

In [13]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [14]:
for question, answer in dataloader:
  print(question, answer[0])

tensor([[45, 89, 90, 91, 92, 42, 93]]) tensor([94])
tensor([[ 10,   2,  65,  66,   3, 286,   5, 287]]) tensor([288])
tensor([[  1,   2,   3,   4,   5, 209]]) tensor([210])
tensor([[  1,   2,   3, 237,   5, 238]]) tensor([135])
tensor([[ 45, 203,   2,  14, 204, 205, 206, 207]]) tensor([208])
tensor([[  1,   2,   3,   4,   5, 289]]) tensor([290])
tensor([[10, 58,  3, 59,  5, 60]]) tensor([61])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[  1,   2,   3, 145, 120,  86,   3, 280, 281]]) tensor([124])
tensor([[ 45,  89,  90, 244, 245,  19,  42, 246]]) tensor([247])
tensor([[ 1,  2,  3,  4,  5, 76]]) tensor([77])
tensor([[ 45, 170,   2,   3,  17, 171, 172]]) tensor([173])
tensor([[  1,  90, 232, 233, 234, 235]]) tensor([236])
tensor([[ 45, 104,   2,   3,  17]]) tensor([105])
tensor([[ 45, 258,   2, 259,  86, 260, 261]]) tensor([262])
tensor([[ 45,  18,   2,   3, 284,  12,   3, 285]]) tensor([208])
tensor([[ 45, 141,   2,  65,  42,   3, 325, 326]]) tensor([6])
tensor([[ 81,  82, 264, 154,  14, 265, 156]]) tensor([39])
tensor([[ 45, 253, 254, 121, 255, 256]]) tensor([257])
tensor([[ 10,  11, 160, 161, 162]]) tensor([163])
tensor([[  1,   2,   3,   4,   5, 139]]) tensor([140])
tensor([[ 10,  99,   3, 100]]) tensor([101])
tensor([[  1,   2,   3,  95, 141,  19,   3,  48]]) tensor([188])
tensor([[  1,   2,   3,   4,   5, 116]]) tensor([117])
tensor([[ 10, 144,   3, 145, 273,  96, 274,   5,   3, 275]]) tensor([276])
tensor([[ 1,  2,  3, 53, 54, 19,  3, 48]]) tensor([55])
tensor([[10, 78, 79]]) tensor([80])
tensor([[ 10,  11, 192, 161, 193]]) tensor([194])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[45, 46, 47, 48, 49, 50, 51]]) tensor([52])
tensor([[ 45, 302, 303, 121,  14, 304, 305, 161, 306, 307, 308, 309]]) tensor([310])
tensor([[ 45, 141,   2, 142,  42, 143]]) tensor([56])
tensor([[ 1,  2,  3, 95, 96, 97]]) tensor([98])
tensor([[  1,   2,   3, 166, 167, 168,  86,  87]]) tensor([169])
tensor([[ 1,  2,  3, 36, 37,  5, 38]]) tensor([39])
tensor([[ 45, 219, 121, 220, 221,  19,  14, 222,  46]]) tensor([223])
tensor([[ 45,   2,   3, 277, 214, 278]]) tensor([279])
tensor([[ 45, 141,   2, 142,  42, 178, 272]]) tensor([102])
tensor([[  1,   2,   3,   4,   5, 102]]) tensor([103])
tensor([[ 45, 321,   2,  65,  66,   3, 322,   5, 323]]) tensor([324])
tensor([[ 1,  2,  3, 72,  5,  3, 73, 74]]) tensor([75])
tensor([[ 10,  78,   3, 299,  19, 300]]) tensor([301])
tensor([[  1,   2,   3,  36,  37,   5, 248]]) tensor([249])
tensor([[  1,   2,   3, 224,   5, 225, 226, 227]]) tensor([228])
tensor([[  1,   2,   3, 125, 126,  19,   3,  48]]) tensor([127])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[  1,   2,   3, 149,  89,  19, 195, 196]]) tensor([197])
tensor([[10,  2,  3, 69,  5, 70]]) tensor([71])
tensor([[ 45, 177,   2,  65,  42, 178, 179,  12, 180, 181]]) tensor([182])
tensor([[ 81,  82, 291,  84,  19,  14, 292]]) tensor([88])
tensor([[ 45, 266, 267,  14, 268, 269, 161, 270]]) tensor([271])
tensor([[81, 82, 83, 84, 85, 86, 87]]) tensor([88])
tensor([[  1,   2,   3,   4,   5, 239, 240]]) tensor([241])
tensor([[ 1,  2,  3,  4,  5, 56]]) tensor([57])
tensor([[  1,   2,   3, 149, 150,  19, 151]]) tensor([152])
tensor([[ 45, 293, 294, 121, 295, 161, 296, 297]]) tensor([298])
tensor([[45, 18,  2, 65, 66,  3, 67, 18]]) tensor([68])
tensor([[ 10,  78, 211]]) tensor([212])
tensor([[ 1,  2,  3, 72,  5, 56]]) tensor([263])
tensor([[  1,   2,   3, 183, 184, 185, 186]]) tensor([187])
tensor([[ 10, 133, 134, 135]]) tensor([136])
tensor([[  1,   2,   3,  40, 137,   5,  26]]) tensor([138])
tensor([[ 81,  82, 198,  84,  19,   3, 199, 200, 201]]) tensor([202])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 81,  82, 153, 154,  14, 155, 156]]) tensor([157])
tensor([[ 1,  2,  3, 29,  5,  3, 30, 10, 31, 32, 33]]) tensor([34, 35])
tensor([[  1,   2,   3,  40,  41,  42, 164]]) tensor([165])
tensor([[ 10, 144,   3, 145,  30,  12, 146,  86,   3, 147]]) tensor([148])
tensor([[  1,   2,   3, 106,   5, 107,  19, 108]]) tensor([109])
tensor([[ 45,   2,   3, 213, 141, 171, 214, 172]]) tensor([116])
tensor([[  1,   2,   3,   4,   5, 282]]) tensor([283])
tensor([[ 10, 311,   3, 312, 313]]) tensor([314])
tensor([[ 10,  78, 114]]) tensor([115])
tensor([[  1,   2,   3,  72,   5, 158]]) tensor([159])
tensor([[ 1,  2,  3, 62, 25,  5, 26, 19, 63]]) tensor([64])
tensor([[ 45,  18, 121,   3, 189, 190]]) tensor([191])
tensor([[ 81,  82, 132,  84,  19,   3,  21,  22]]) tensor([39])
tensor([[  1,   2,   3,  17, 118,  86,  87]]) tensor([119])
tensor([[ 10,  99,   3, 107, 242]]) tensor([243])
tensor([[ 45, 110,   2, 111,  19, 112]]) tensor([113])
tensor([[ 45, 141,   2, 229,  12,   3, 230, 231]]) tensor([158])
tensor([[ 45, 120, 121,   3, 122,  97, 123]]) tensor([124])
tensor([[ 45, 141, 121,   3, 250,   5, 251]]) tensor([252])
tensor([[  1,   2,   3,   4,   5, 112]]) tensor([320])
tensor([[ 1,  2,  3, 40, 41, 42, 43]]) tensor([44])
tensor([[ 45, 315,   2, 316,  65,  66,   3, 317, 318]]) tensor([319])
tensor([[  1,   2,   3, 215,   5,  14, 216, 217]]) tensor([218])
tensor([[ 10, 144,   3, 145, 174,   5,   3,  73, 175]]) tensor([176])
tensor([[ 45, 128,   2,  65,  66,   3, 129, 130]]) tensor([131])

In [15]:
import torch.nn as nn

In [16]:
# understanding applied Here...
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [17]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [18]:
learning_rate = 0.001
epochs = 20

In [19]:
model = SimpleRNN(len(vocab))

In [20]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [23]:
import torch.nn as nn

# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    # Ensure target is a single token for CrossEntropyLoss
    loss = criterion(output, answer[0][0].unsqueeze(0))

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 477.616527
Epoch: 2, Loss: 402.462944
Epoch: 3, Loss: 334.836679
Epoch: 4, Loss: 281.649092
Epoch: 5, Loss: 232.056821
Epoch: 6, Loss: 187.387256
Epoch: 7, Loss: 147.702164
Epoch: 8, Loss: 114.319915
Epoch: 9, Loss: 87.959401
Epoch: 10, Loss: 67.622118
Epoch: 11, Loss: 52.511784
Epoch: 12, Loss: 41.471770
Epoch: 13, Loss: 33.183538
Epoch: 14, Loss: 27.431636
Epoch: 15, Loss: 22.713163
Epoch: 16, Loss: 18.992064
Epoch: 17, Loss: 16.003728
Epoch: 18, Loss: 13.674480
Epoch: 19, Loss: 11.920474
Epoch: 20, Loss: 10.288092

In [24]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [27]:
predict(model, "What is the name of the person who wote this project?")

maanaav

In [31]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'name': 29,
 'person': 30,
 'wote': 31,
 'this': 32,
 'project': 33,
 'maanaav': 34,
 'trivedi': 35,
 'square': 36,
 'root': 37,
 '64': 38,
 '8': 39,
 'chemical': 40,
 'symbol': 41,
 'for': 42,
 'gold': 43,
 'au': 44,
 'which': 45,
 'year': 46,
 'did': 47,
 'world': 48,
 'war': 49,
 'ii': 50,
 'end': 51,
 '1945': 52,
 'longest': 53,
 'river': 54,
 'nile': 55,
 'japan': 56,
 'tokyo': 57,
 'developed': 58,
 'theory': 59,
 'relativity': 60,
 'albert-einstein': 61,
 'freezing': 62,
 'fahrenheit': 63,
 '32': 64,
 'known': 65,
 'as': 66,
 'red': 67,
 'mars': 68,
 'author': 69,
 '1984': 70,
 'george-orwell': 71,
 'currency': 72,
 'united': 73,
 'kingdom': 74,
 'pound': 75,
 'india': 76,
 'delhi': 77,
 'discovered': 78,
 'gravity': 79,
 'newton': 80,
 'how': 81,
 'many': 82,
 'continents': 83,
 'are': 84,
 'there': 85,
 'on': 86,
 'earth': 87,
 '7': 88,
 'gas': 89,
 'do': 90,
 'plants': 91,
 'use': 92,
 'photosynthesis': 93,
 'co2': 94,
 'smallest': 95,
 'prime': 96,
 'number': 97,
 '2': 98,
 'invented': 99,
 'telephone': 100,
 'alexander-graham-bell': 101,
 'australia': 102,
 'canberra': 103,
 'ocean': 104,
 'pacific-ocean': 105,
 'speed': 106,
 'light': 107,
 'vacuum': 108,
 '299,792,458m/s': 109,
 'language': 110,
 'spoken': 111,
 'brazil': 112,
 'portuguese': 113,
 'penicillin': 114,
 'alexander-fleming': 115,
 'canada': 116,
 'ottawa': 117,
 'mammal': 118,
 'whale': 119,
 'element': 120,
 'has': 121,
 'atomic': 122,
 '1': 123,
 'hydrogen': 124,
 'tallest': 125,
 'mountain': 126,
 'everest': 127,
 'city': 128,
 'big': 129,
 'apple': 130,
 'newyork': 131,
 'planets': 132,
 'painted': 133,
 'starry': 134,
 'night': 135,
 'vangogh': 136,
 'formula': 137,
 'h2o': 138,
 'italy': 139,
 'rome': 140,
 'country': 141,
 'famous': 142,
 'sushi': 143,
 'was': 144,
 'first': 145,
 'step': 146,
 'moon': 147,
 'armstrong': 148,
 'main': 149,
 'ingredient': 150,
 'guacamole': 151,
 'avocado': 152,
 'sides': 153,
 'does': 154,
 'hexagon': 155,
 'have': 156,
 '6': 157,
 'china': 158,
 'yuan': 159,
 'pride': 160,
 'and': 161,
 'prejudice': 162,
 'jane-austen': 163,
 'iron': 164,
 'fe': 165,
 'hardest': 166,
 'natural': 167,
 'substance': 168,
 'diamond': 169,
 'continent': 170,
 'by': 171,
 'area': 172,
 'asia': 173,
 'president': 174,
 'states': 175,
 'george-washington': 176,
 'bird': 177,
 'its': 178,
 'ability': 179,
 'mimic': 180,
 'sounds': 181,
 'parrot': 182,
 'longest-running': 183,
 'animated': 184,
 'tv': 185,
 'show': 186,
 'simpsons': 187,
 'vaticancity': 188,
 'most': 189,
 'moons': 190,
 'saturn': 191,
 'romeo': 192,
 'juliet': 193,
 'shakespeare': 194,
 'earths': 195,
 'atmosphere': 196,
 'nitrogen': 197,
 'bones': 198,
 'adult': 199,
 'human': 200,
 'body': 201,
 '206': 202,
 'metal': 203,
 'liquid': 204,
 'at': 205,
 'room': 206,
 'temperature': 207,
 'mercury': 208,
 'russia': 209,
 'moscow': 210,
 'electricity': 211,
 'benjamin-franklin': 212,
 'second-largest': 213,
 'land': 214,
 'color': 215,
 'ripe': 216,
 'banana': 217,
 'yellow': 218,
 'month': 219,
 '28': 220,
 'days': 221,
 'common': 222,
 'february': 223,
 'study': 224,
 'living': 225,
 'organisms': 226,
 'called': 227,
 'biology': 228,
 'home': 229,
 'great': 230,
 'wall': 231,
 'bees': 232,
 'collect': 233,
 'from': 234,
 'flowers': 235,
 'nectar': 236,
 'opposite': 237,
 'day': 238,
 'south': 239,
 'korea': 240,
 'seoul': 241,
 'bulb': 242,
 'edison': 243,
 'humans': 244,
 'breathe': 245,
 'survival': 246,
 'oxygen': 247,
 '144': 248,
 '12': 249,
 'pyramids': 250,
 'giza': 251,
 'egypt': 252,
 'sea': 253,
 'creature': 254,
 'eight': 255,
 'arms': 256,
 'octopus': 257,
 'holiday': 258,
 'celebrated': 259,
 'december': 260,
 '25': 261,
 'christmas': 262,
 'yen': 263,
 'legs': 264,
 'spider': 265,
 'sport': 266,
 'uses': 267,
 'net,': 268,
 'ball,': 269,
 'hoop': 270,
 'basketball': 271,
 'kangaroos': 272,
 'female': 273,
 'minister': 274,
 'uk': 275,
 'margaretthatcher': 276,
 'fastest': 277,
 'animal': 278,
 'cheetah': 279,
 'periodic': 280,
 'table': 281,
 'spain': 282,
 'madrid': 283,
 'closest': 284,
 'sun': 285,
 'father': 286,
 'computers': 287,
 'charlesbabbage': 288,
 'mexico': 289,
 'mexicocity': 290,
 'colors': 291,
 'rainbow': 292,
 'musical': 293,
 'instrument': 294,
 'black': 295,
 'white': 296,
 'keys': 297,
 'piano': 298,
 'americas': 299,
 '1492': 300,
 'christophercolumbus': 301,
 'disney': 302,
 'character': 303,
 'long': 304,
 'nose': 305,
 'grows': 306,
 'it': 307,
 'when': 308,
 'lying': 309,
 'pinocchio': 310,
 'directed': 311,
 'movie': 312,
 'titanic': 313,
 'jamescameron': 314,
 'superhero': 315,
 'also': 316,
 'dark': 317,
 'knight': 318,
 'batman': 319,
 'brasilia': 320,
 'fruit': 321,
 'king': 322,
 'fruits': 323,
 'mango': 324,
 'eiffel': 325,
 'tower': 326}

In [32]:
list(vocab.keys())[35]

'trivedi'

In [29]:
# extra for understanding
#solution
x =nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True) #[1,1,64]
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e =z(d.squeeze(0)) # removing extra dimension using unsqueeze

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [30]:
# problem
x =nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e =z(d)

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 6, 64])
shape of e: torch.Size([1, 6, 324])